ALTER TABLE "BulkJob" ADD COLUMN "reacherEmails" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BulkJob" ADD COLUMN "prefilteredEmails" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BulkJob" ADD COLUMN "noMxRows" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BulkJob" ADD COLUMN "disposableRows" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BulkJob" ADD COLUMN "mxLookupFailedRows" INTEGER NOT NULL DEFAULT 0;
